server:
  port: 9092

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: user
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/TestAppointmentDB
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update